# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci_prom21" "ahci" "xhci_pci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-eb01f201-8e55-43ec-b84f-1b7525a8cbc9";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-eb01f201-8e55-43ec-b84f-1b7525a8cbc9".device = "/dev/disk/by-uuid/eb01f201-8e55-43ec-b84f-1b7525a8cbc9";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B187-F0A7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-9bec161e-8953-4dd7-a787-6ba9b8f8666c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
